config/routes.rb
Wildthing::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  match "markdown_preview" => "application#markdown_preview"
  
  devise_for :admin_users, ActiveAdmin::Devise.config

	resources :projects, :only => [:show,:index]
	resources :ideas, :only => [:create,:index]
	resources :posts, :only => [:show,:index]
	resources :pledges, :only => [:create]
	resources :partners, :only => [:index]
	
	match "pledge" => "pledges#new"
  match "manifesto" => "home#manifesto"
  match "privacy" => "home#privacy"
  match "the-nature-film" => "home#film", :as => "film"
  
  root :to => "home#index"
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end

app/models/category.rb
class Category < ActiveRecord::Base

	attr_accessible :title
	validates_presence_of :title
	
	has_many :projects
	
	extend FriendlyId
  friendly_id :title, use: :slugged
  
end

app/models/idea.rb
class Idea < ActiveRecord::Base

	attr_accessible :title, :idea, :name, :twitter_handle, :published	
	validates_presence_of :title, :idea, :name
	
	def self.published
    self.order('created_at DESC').where('published = true')
  end
  
  def self.unpublished
    self.order('created_at DESC').where('published = false')
  end
  
end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base

	attr_accessible :vimeo_id, :title
	validates_presence_of :vimeo_id, :title

end

app/models/partner.rb
class Partner < ActiveRecord::Base

	attr_accessible :url, :name, :image, :priority
		
	validates_presence_of :name, :url
	
  before_save :check_url_scheme
  
  mount_uploader :image, ImageUploader

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

	attr_accessible :name, :facebook, :twitter, :email, :subscribed
	
	validates_presence_of :name, :email
	validates_uniqueness_of :email, :message => "You have already pledged using this email address"
  
end

app/models/post.rb
class Post < ActiveRecord::Base

	attr_accessible :title, :body, :abstract, :image
	validates_presence_of :title, :body, :abstract
		
	extend FriendlyId
  friendly_id :title, use: :slugged
  
  mount_uploader :image, ImageUploader
  
  paginates_per 10
  
end

app/models/project.rb
class Project < ActiveRecord::Base

	attr_accessible :title, :description, :url, :image, :category_id, :featured, :body
		
	validates_presence_of :title, :description
		
	belongs_to :category
	
	extend FriendlyId
  friendly_id :title, use: :slugged
  
  before_save :check_url_scheme
  
  mount_uploader :image, ImageUploader
  
  def self.featured
    self.where('featured = true').limit(4) || nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def markdown_preview
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    render :inline => markdown.render(params[:data]).html_safe
  end
  
  def not_found
    respond_to do |format|
      format.html { render 'errors/404', :status => 404 }
      format.any { render 'errors/404', :status => 404, :formats => [:html], :layout => 'application', :content_type => Mime[:html] }
    end
  end
  
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
    not_found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
    @wild_thing_projects = Category.find_by_title('Wild Thing').projects.limit(2)
    @projects = Project.featured
  
    @inspirations = Inspiration.order('created_at DESC').limit(1)
    
    @ideas = Idea.where('published = true').order('created_at DESC').limit(3)
    @idea = Idea.new
    
    @pledge_count = Pledge.count
    @pledge = Pledge.new

		@post = Post.order('created_at DESC').first
    
  end
  
  def manifesto
    @pledge = Pledge.new
  end

  def film
    @inspirations = Inspiration.all
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	def create
	  @idea = Idea.new(params[:idea])
    if @idea.save
      flash[:notice] = "Thanks for adding to the conversation! We'll publish your idea soon."
      redirect_to ideas_path
    else
      redirect_to index_path
    end
	end
	
	def index
	  @ideas = Idea.published
	end

end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

	def index
	  @partners = Partner.order('priority ASC').all
	end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

	def create
	  
	  @pledge = Pledge.new(params[:pledge])
	  	  
    if @pledge.save
      
      session[:pledged] = true
      
      #if @pledge.subscribed?
      #  mc = Gibbon.new('932a6959829feb080dd18797db38d42d-us5')
      #  puts mc.list_subscribe({:id => '7bbb79ac57', :email_address => @pledge.email, :double_optin => true})
      #end
      
      redirect_to projects_path
      
    else
      
      flash[:notice] = "Sorry, we couldn't save your pledge, it looks like you've pledged before."
      redirect_to root_path
      
    end
    
	end
	
	def new
	  redirect_to root_path
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find_by_slug(params[:id])
  end
  
  def index
    @posts = Post.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    @categories = Category.where("title != 'Wild Thing'")
  end

	def show
	  @project = Project.find_by_slug(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML,:autolink => true, :space_after_headers => true)
  end
  
  def is_home?
    params[:controller] == "home" && params[:action] == "index"
  end
  
  def is_manifesto?
    params[:controller] == "home" && params[:action] == "manifesto"
  end
  
  def is_projects?
    params[:controller] == "projects"
  end
  
  def is_film?
    params[:controller] == "home" && params[:action] == "film"
  end
  
end

app/views/home/_footnotes.html.erb
<section class="footnotes">
	
	<h2>Background information</h2>
	
	<ol>
		<li id="cite_1">The Lancet: "More people die globally from inactivity than from smoking." <cite><a href="http://www.thelancet.com/series/physical-activity">Source</a></cite></li>
		<li id="cite_2">In England, prescribing of ADHD drugs to under-16s went up by 33% between 2005 and 2007. Anti-depressant drugs may also increase the risk of obesity in children. Encouraging more children with ADHD to take up active play and sport in safe, green spaces could beat natural and effective alternative to medication, improving other health and wellbeing outcomes. <cite><a href="http://www.fph.org.uk/uploads/r_great_outdoors.pdf">Source</a>, <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2242642/">Source</a></cite</li>
		<li id="cite_3">Mental health problems have not only a human and social cost, but also an economic one, with wider costs in England amounting to £105.2 billion a year. Mental illness is the single largest cost to the National Health Service (NHS) at £10.4 billion (10.8% of the NHS budget). In 2007, service costs in England, which include the NHS, social and informal care, amounted to £22.5 billion and these costs are projected to in- crease by 45%, to £32.6 billion by 2026. <cite><a href="http://www.rcpsych.ac.uk/pdf/Position%20Statement%204%20website.pdf">Source</a></cite></li>
		<li id="cite_4">Even a walk in a park can have the same level of benefits as medication. 'Natural' environments in urban settings can increase the likelihood of physical activity and play. Children who play in green spaces also develop better motor skills than those who don't. <cite><a href="http://www.fph.org.uk/uploads/r_great_outdoors.pdf">Source</a></cite></li>
		<li id="cite_6">UNICEF: "In the UK, we are raising the unhappiest kids in the developed world" <ctie><a href="http://www.unicef-irc.org/publications/pdf/rc7_eng.pdf">Source</a></cite></li>
		<li id="cite_7">Childhood happiness is closely linked to time spent outdoors. <a href="http://www.unicef.org.uk/Latest/News/Research-shows-UK-children-caught-in-materialistic-trap">Source</a></cite></li>
		<li id="cite_8">The roaming radius for kids has declined by 90 per cent in thirty years. <cite>Gaster, S. 'Urban Children's Access to Their Neighbourhoods: Changes Over Three Generations', quoted in Louv, R. (2005) Last Child in the Woods, p.123</cite></li>
		<li id="cite_9">CHILDWISE estimate that children aged 5&ndash;16 spend 2.5 hours watching television every day, 1.6 hours on computers and the internet, 1.3 hours gaming and 1.1 hours on a mobile phone. <cite><a href="http://www.childwise.co.uk/">Source</a></ctie></li>
	</ol>

</section>

app/views/home/backing.html.erb
<ul class="grid_list">
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "Green Lions"), "http://greenlions.com/" %></li>
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "Do Lectures"), "http://www.dolectures.com" %></li>
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "TYF"), "http://www.tyf.com/" %></li>
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "Eden Project"), "http://www.edenproject.com/" %></li>
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "Al Kennedy"), "https://twitter.com/_alkennedy" %></li>
	<li><%= link_to (image_tag "branding/greenlions.gif", :alt => "National Trust"), "http://www.nationaltrust.org.uk/" %></li>
</ul>

app/views/home/film.html.erb
<h1>The Nature Film</h1>

<iframe id="vimeoembed" src="http://player.vimeo.com/video/44097760?title=0&amp;byline=0&amp;portrait=0&amp;color=b8d432" width="960" height="539" frameborder="0"></iframe>

<p>Project Wild Thing is the core part of a feature documentary of the same name, made in collaboration with the Channel 4 Britdoc Foundation, Good For Nothing, the National Trust, the RSPB, and the NHS.</p>
<p>According to UNICEF, children in the UK are the unhappiest kids in the western world. Plenty of food, millions of TV channels, the internet, Wii, no wars to worry about &ndash; when there’s so much to be happy about, what’s going on? Shiny screens in every room, increased parental fears of dirt and the unknown and the elimination of free public space are all converging to create a generation that has no connection with nature. So what can we do to get parents and kids out into the woods?</p>
<p>Filmmaker DAVID BOND thinks Mother Nature needs a helping hand getting his kids to forget the distractions of the modern world and wake up to the benefits of nature. He appoints himself the Marketing Director for Nature and, with the help of advertising and marketing experts, he sets out to persuade apathetic consumers, and his family, of the benefits of this amazing, free, wonder-product. </p>

<% if @inspirations.any? %>
<section class="full_panel">
	<ul class="grid grid_film">
		<% @inspirations.each do |inspiration| %>
			<%= render :partial => "inspirations/block", :locals => { :inspiration => inspiration } %>
		<% end %>
	</ul>
</section>
<% end %>

app/views/home/index.html.erb
<section id="projects">
	
	<% if @wild_thing_projects.any? %>
	<ul class="grid grid_two">
		<% @wild_thing_projects.each do |project| %>
		<li>
			<h2>
				<% unless project.body.blank? %>
					<%= link_to project.title, project_path(project) %>
				<% else %>
					<%= link_to project.title, project.url %>
				<% end %>
			</h2>
			<p><%= project.description %></p>
			<% unless project.image.url.nil? %>
							
				<% unless project.body.blank? %>
					<%= link_to image_tag(project.image), project_path(project) %>
				<% else %>
					<%= link_to image_tag(project.image), project.url %>
				<% end %>
				
			<% end %>

		</li>
		<% end %>
	</ul>
	<% end %>
	
	<% if @projects.any? %>
	<ul class="grid">
		<% @projects.each do |project| %>
		<li>
			<h3><%= link_to project.title, project.url %></h3>
			<p><%= project.description %></p>
		</li>
		<% end %>
	</ul>
	<% end %>
	
	<p class="cta"><%= link_to "How to get wild", projects_path %></p>

</section>

<% if @inspirations.any? %>
<section class="full_panel" id="inspiration">

	<div class="heading">
		<h1>Inspiration</h1>
		<h2>It's time to re-connect with nature</h2>
	</div>
	
	<ul class="grid grid_film">
		
		<% @inspirations.each do |inspiration| %>
			<%= render :partial => "inspirations/block", :locals => { :inspiration => inspiration } %>
		<% end %>
		
		<% if @post.present? %>
			<%= render :partial => "posts/block", :locals => { :post => @post } %>
		<% end %>
		
	</ul>

	<p class="cta"><%= link_to "The Nature Film", film_path %></p>

</section>
<% end %>

app/views/home/manifesto.html.erb
<section class="full_panel">
		
	<h1>The Wild Thing Manifesto</h1>	
	<p>For 2 million years the idea of being separate from nature did not even occur to humans. We were nature, and nature was us. But recently we’ve turned our backs on nature. Thanks to technology and the comforts it has provided we are now the safest, fattest and most indoor human beings ever. And it is getting worse every day.<a class="cite" href="#cite_1">[1]</a></p>
	<p class="pull">Children today are getting dangerously tame<a class="cite" href="#cite_2">[2]</a></p> 
	<p>We need your help to change that and make them wild. In the UK we are raising the unhappiest children in the developed world.<a class="cite" href="#cite_6">[6]</a><a class="cite" href="#cite_3">[3]</a> We give them plenty of food, millions of TV channels, the Internet and computer games. What is going on? What are they unhappy about?</p>
	<p class="pull">THE LURE OF THE INDOORS IS CREATING A GENERATION THAT HAS NO CONNECTION WITH NATURE</p>
	<p>Stepping outside and connecting with nature is both a small step out of your door, and a wild leap into a new way of life. Children in the UK (aged 5 – 16) spend 2.5 hours every day watching TV and 1.7 hours every day online.<a class="cite" href="#cite_9">[9]</a></p>
	<p class="pull">THAT IS OVER 4 HOURS SCREEN TIME PER DAY</p>
	<p>Given the chance, children love being outdoors &ndash; contact with nature is fun, free and keeps them fit.<a class="cite" href="#cite_7">[7]</a> For us it reduces stress, boosts our immune systems and gives us a better perspective on problems<a class="cite" href="#cite_4">[4]</a>. We could do with more of that right now.</p>
	<p>If we don't act, a generation of children will miss out on developing a proper connection with nature<a class="cite" href="#cite_8">[8]</a> that will last for their whole life. As a species we will lose vital natural knowledge. We need children to be future custodians of the natural world.</p>
	<p>The Wild Thing Pledge is your promise to spend as much time outside every day as you do on screens. Match your screen time with wild time. And encourage your children to do the same.</p>
	
</section>

<section class="full_panel">
	<h2>Take the pledge</h2>
	<%= render "pledges/form" %>
</section>

app/views/home/privacy.html.erb
<h1>Project Wild Thing Privacy Policy</h1>

<h2>Use of Personal Information</h2>
<p>We will never pass your information on to any third parties. Ever. If you have opted in to receive updates we may occasionally send you information related to the Wild Thing project by email.</p>

<h2>Log Files and Cookies</h2>
<p>This website utilises industry standard analytics packages which gathers limited information on visitors to our website automatically, and stores this anonymous information in server log files. This information may include IP addresses, browser type, basic IP information, referring pages, operating system used and date/time stamps. This information does not identify individual users; it is used only for site administration, as well as for analysis of website usage and trends.</p>
<p>Additionally, cookies may be used to provide easier and faster access to website features such as logins and/or repeat visits. Cookies are very small text files that are stored on personal computers for reference purposes. We do not link the information we store in cookies to any personally identifiable information you have submitted while on our site.</p>
<p>We use both session ID cookies and persistent cookies. A session cookie expires when your browser is closed, and a persistent cookie may stay on your hard drive for an extended period. Session cookies make it easier for you to navigate our site; persistent cookies can perform such activities as storing your password for forums or blogs so you do not have to sign in every time you visit those areas, and/or may be used to enable us to track and target the interests of our users so as to enhance the overall experience of using our site.</p>
<p>We have no access to or administration abilities over any cookies that are used by any advertisers on our site.</p>

<h2>Links to Other Websites</h2>
<p>This website may contain links to other sites that are not controlled in any way by us. Please be aware of this when you click on any such links; we are not responsible for the privacy practices and/or policies of any website other than our own. Consequently, we strongly suggest that you  review the privacy policy of every website you visit, whether or not they are linked to by our own site.</p>

<h2>Legal Disclaimer</h2>
<p>We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order or legal process served on our website.</p>

<h2>Contact Details</h2>
<p>If you have any questions or concerns regarding this privacy policy, or you wish to contact us by <a href="mailto:andrew@goodfornothing.com">email</a>.</p>
<p>This privacy policy was last updated on 31 August 2012.</p>

app/views/ideas/_block.html.erb
<li>
	<p class="name">Idea from <em><%= idea.name %></em></p>
	<p class="idea"><%= idea.title %></p>
</li>

app/views/ideas/_form.html.erb
<%= simple_form_for [@idea] do |f| %>
  
	<p>How can we re-connect our kids with nature?</p>
	<%= field_set_tag nil, :class => "auto" do %>
		<%= f.input :name, :input_html => { :"data-placeholder" => "Your name" } %>
		<%= f.input :title, :as => :text, :input_html => { :"data-placeholder" => "Your idea (in under 90 characters)" } %>
		<%= f.input :idea, :as => :text, :input_html => { :"data-placeholder" => "More about your idea, supporting information etc." } %>
	<% end %>

	<%= field_set_tag do %>
		<%= f.submit :value => "Inspire us" %>
	<% end %>
  
<% end %>

app/views/ideas/_panel.html.erb
<section id="ideas">

	<h2>Share your ideas</h2>
	
	<%= render "ideas/form" %>

	<% if @ideas.any? %>
	
	<div class="user_ideas">
				
		<ul id="idea_list">
			<% @ideas.each do |idea| %>
				<%= render :partial => "ideas/block", :locals => { :idea => idea } %>
			<% end %>
		</ul>
		
		<p class="call"><%= link_to "More ideas", ideas_path %></p>
		
	</div>
	<% end %>
	
</section>

app/views/ideas/index.html.erb
<h1>How can we re-connect with nature?</h1>

<section class="user_ideas">
	<% if @ideas.any? %>
	<ul>
		<% @ideas.each do |idea| %>
			<li>
				<p class="name">Idea from <em><%= idea.name %></em></p>
				<p class="idea"><%= idea.title %></p>
				<%= simple_format idea.idea %>
			</li>	
		<% end %>
	</ul>
	<% end %>
</section>

app/views/inspirations/_block.html.erb
<li>
	<iframe id="vimeoembed" src="http://player.vimeo.com/video/<%= inspiration.vimeo_id %>?title=0&amp;byline=0&amp;portrait=0&amp;color=b8d432" width="461" height="259" frameborder="0"></iframe>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		
		<title>Wild Thing &mdash; Re-connecting kids with nature</title>
		<meta name="description" content="Ideas, inspiration and activities to re-connect kids with nature." />
		<meta name="keywords" content="kids, nature, deficit, disorder, wild, thing" />
		<link rel="shortcut icon" href="/favicon.ico" />
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		
		<meta property="fb:admins" content="1009211182" />
		
		<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
		
		 <% if Rails.env.production? %>
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-34329419-1']);
		  _gaq.push(['_setDomainName', 'projectwildthing.com']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
		<% end %>
			
	</head>
	<body class="<%= "section_#{params[:controller]} view_#{params[:action]} pledged_#{session[:pledged]}"%>">
		
		<header>
			
			<section class="introduction">
			
				<div class="container">
					
					<% if is_home? %>
					
						<h1 class="branding ir">Project Wild Thing<span></span></h1>
						<p class="tagline">Re-connecting 1 million kids with nature</p>
						
						<%= render "pledges/introduction" unless session[:pledged] %>
						<%= render "pledges/pledged" if session[:pledged] %>
						
						<nav id="primary_navigation">
							<ul>
								<li><%= link_to "Find a project", "#projects" %></li>
								<li><%= link_to "Be Inspired", "#inspiration" %></li>
								<li><%= link_to "Share Your Ideas", "#ideas" %></li>
							</ul>
						</nav>
					
					<% else %>
					
						<p class="branding"><a href="<%= root_path %>" class="ir">Project Wild Thing <span></span></a></p>
						<p class="tagline">Re-connecting 1 million kids with nature</p>
												
						<nav id="primary_navigation">
							<ul>
								<li><%= link_to "Find a project", projects_path, :class => ("active" if is_projects?) %></li>
								<li><%= link_to "Be Inspired", film_path, :class => ("active" if is_film?) %></li>
								<li><%= link_to "Share Your Ideas", "#{root_path}#ideas" %></li>
							</ul>
						</nav>
						
					<% end %>
						
					<% if session[:pledged] && is_projects?	%>
					
						<div class="sharing">		
							<p class="cta"><a href="https://twitter.com/intent/tweet?&amp;via=wearewildthing&amp;url=http%3A%2F%2Fwww.projectwildthing.com&amp;text=I have pledged to spend as much time outdoors as I do looking at screens, take the pledge with me:">Tweet your Pledge</a></p>
							<p class="cta"><a href="http://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.projectwildthing.com&amp;text=I have pledged to spend as much time outdoors as I do looking at screens, take the pledge with me">Share on Facebook</a></p>
						</div>
						
					<% end %>
						
				</div>
			
			</section>
			
		</header>
		
		<div id="primary_content" role="main">
			<div class="container">
				<% if flash[:notice] %>
					<p class="notice"><%= flash[:notice] %></p>
				<% end %>
				<%= yield %>
			</div>
		</div>
				
		<footer>
			<div class="container">
				<%= render "ideas/panel" if is_home? %>
				<%= render "home/footnotes" if is_manifesto? %>
				<p class="colophon">A Wild Thing <%= link_to "founders", partners_path %> collaboration, Designed <a href="http://www.becausestudio.co.uk/">Because Studio</a>, Twittering at <a href="http://twitter.com/wearewildthing">@wearewildthing</a>, Privacy in our <%= link_to "policy", privacy_path %>, <%= link_to "Get in touch", "mailto:hello@greenlions.com" %></p>
			</div>
		</footer>
			
	</body>
</html>

app/views/partners/index.html.erb
<h1>The Wild Thing Founding Partners</h1>

<% if @partners.any? %>
	<ul class="grid">
		<% @partners.each do |partner| %>
			<% unless partner.image.nil? %>
			<li><%= link_to (image_tag partner.image.grid, :alt => partner.name), partner.url %></li>
			<% end %>
		<% end %>
	</ul>
<% end %>

app/views/pledges/_form.html.erb
<%= simple_form_for [@pledge] do |f| %>
  
	<%= field_set_tag nil, :class => "auto" do %>
		<%= f.input :name, :input_html => { :"data-placeholder" => "Your name" } %>
		<%= f.input :email, :input_html => { :"data-placeholder" => "Your email address" } %>
	<% end %>

	<%= field_set_tag nil, :class => "actions" do %>
		<%= f.input :subscribed, :label => "Keep me updated" %>
		<%= f.submit :value => "Pledge" %>	
	<% end %>
	
<% end %>

app/views/pledges/_introduction.html.erb
<div class="panels">

	<section id="manifesto" class="panel">
		<p class="goal"><span><%= "%04d" %  (@pledge_count.to_i) %></span> people have pledged</p>
		<p class="pledge">I promise to spend as much of my <span class="tip" title="Not including time spent at work!">time</span> outdoors as I do looking at screens, and, by my advice and example, encourage others to do the same</p>
		<p class="cta"><%= link_to "Read the Manifesto", manifesto_path %></p>
	</section>

	<section id="pledge" class="panel">
		<h2>Take the wild thing pledge</h2>
		<%= render "pledges/form" %>
	</section>

</div>

app/views/pledges/_pledged.html.erb
<div class="panels">

	<section id="manifesto" class="panel">
		<p class="goal"><span><%= "%04d" %  (@pledge_count.to_i) %></span> people have pledged</p>
		<p class="pledge">I promise to spend as much of my <span class="tip" title="Not including time spent at work!">time</span> outdoors as I do looking at screens, and, by my advice and example, encourage others to do the same</p>
		<p class="cta"><%= link_to "Read the Manifesto", manifesto_path %></p>
	</section>

	<section id="pledge" class="panel">
		<div class="sharing">		
			<h2>Spread the word</h2>
			<p class="cta"><a href="https://twitter.com/intent/tweet?&amp;via=wearewildthing&amp;url=http%3A%2F%2Fwww.projectwildthing.com&amp;text=I have pledged to spend as much time outdoors as I do looking at screens, take the pledge with me:">Tweet your Pledge</a></p>
			<p class="cta"><a href="http://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.projectwildthing.com&amp;text=I have pledged to spend as much of my free time outdoors as I do looking at screens, take the pledge with me">Share on Facebook</a></p>
		</div>
	</section>

</div>

app/views/posts/_block.html.erb
<li class="post_block">
	<% unless @post.image.url.nil? %>
	<%= link_to (image_tag @post.image.inspiration), post_path(@post) %>
	<% end %>
	<h3><%= link_to @post.title, post_path(@post) %></h3>
	<p><%= @post.abstract %></p>
</li>

app/views/posts/index.html.erb
<% if @posts.any? %>
	<% @posts.each do |post| %>
		<%= render "block", :post => post %>
	<% end %>
<% end %>

app/views/posts/show.html.erb
<% if @post %>
	<article>
	<h2><%= @post.title %></h2>
	<time>Posted <%= @post.created_at.to_s(:article) %></time>
	<%= markdown.render(@post.body).html_safe %>
	</article>
<% end %>

app/views/projects/_block.html.erb
<li>
	<h3>
	<% if project.body.blank? || project.body.nil? %>
		<%= link_to project.title.html_safe, project.url %>
	<% else %>
		<%= link_to project.title.html_safe, project_path(project) %>
	<% end %>
	</h3>
	<%= markdown.render(project.description).html_safe %>
</li>

app/views/projects/index.html.erb
<% if @categories.any? %>

	<ul class="categories">
		<% @categories.each do |category| %>
		<li><a href="#<%= category.slug %>"><%= category.title %></a></li>
		<% end %>
	</ul>
	
	<p style="text-align: center;">Projects to help get outdoors more with your kids</p>
	
	<% @categories.each do |category| %>
		<section class="project_category">
			<h2 id="<%= category.slug %>"><%= category.title %></h2>
			<% if category.projects.any? %>
			<ul class="grid grid_four">
				<% category.projects.each do |project| %>
					<%= render :partial => "block", :locals => { :project => project } %>
				<% end %>
			</ul>
			<% end %>
		</section>
	<% end %>
		
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<% unless @project.image.url.nil? %>
	<%= image_tag @project.image %>
<% end %>

<section class="full_panel">
<%= markdown.render(@project.body).html_safe %>
</section>